name: test

on:
  push:
  schedule:
    - cron: "*/5 * * * *"

jobs:

  test:

    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.6"
          - "3.8"

    runs-on: ubuntu-18.04

    steps:

      - name: Show environment variables
        run: |
          env | sort

      - name: Set environment variables
        # TOXENV=py36
        # ARTIFACT_SUFFIX=bhrutlege-gh-actions-test-1234567890
        run: |
          echo TOXENV=py${{ matrix.python-version }} | tr -d . >> $GITHUB_ENV
          echo ARTIFACT_SUFFIX=$GITHUB_REPOSITORY-$GITHUB_RUN_ID | tr / - >> $GITHUB_ENV

      - name: Write JSON
        run: |
          echo '{
            "one": 1,
            "two": "2"
          }' > test.json
          python3 -m json.tool test.json

      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache tox environments
        uses: actions/cache@v2
        with:
          path: |
            .tox
          key: ${{ runner.os }}-pip-${{ matrix.python-version }}-${{ hashFiles('requirements.txt', 'tox.ini') }}

      - name: Install dependencies
        run: |
          python -m pip install tox

      - name: Run ${{ env.TOXENV }} tests
        run: |
          python -m tox -- --color=yes

      - name: Upload ${{ env.TOXENV }} coverage
        uses: actions/upload-artifact@v2
        with:
          name: coverage-${{ env.TOXENV }}-${{ env.ARTIFACT_SUFFIX }}
          path: htmlcov-${{ env.TOXENV }}
