name: test

on:
    push:

jobs:
    test:
        strategy:
            matrix:
                python:
                    - "3.6"
        runs-on: ubuntu-18.04
        steps:
            - uses: actions/setup-python@v2
              with:
                  python-version: ${{ matrix.python }}
            - name: Install dependencies
              run: |
                sudo apt-get update
                sudo apt-get install libcurl4-openssl-dev
                python -m pip install pycurl
